export const PRODUCT_SHORT_NAME = "prs";
export const LEGACY_PRODUCT_SHORT_NAME = "git-ai";
export const PRODUCT_DISPLAY_NAME = "Pull Request Smith";

export const PACKAGE_SCOPE = "@prs";
export const LEGACY_PACKAGE_SCOPE = "@git-ai";

export const REPOSITORY_STATE_DIRECTORY = ".prs";
export const LEGACY_REPOSITORY_STATE_DIRECTORY = ".git-ai";

export const REPOSITORY_CONFIG_RELATIVE_PATH = `${REPOSITORY_STATE_DIRECTORY}/config.json`;
export const LEGACY_REPOSITORY_CONFIG_RELATIVE_PATH =
  `${LEGACY_REPOSITORY_STATE_DIRECTORY}/config.json`;

export const PR_ASSISTANT_START_MARKER = "<!-- prs:pr-assistant:start -->";
export const PR_ASSISTANT_END_MARKER = "<!-- prs:pr-assistant:end -->";
export const LEGACY_PR_ASSISTANT_START_MARKER = "<!-- git-ai:pr-assistant:start -->";
export const LEGACY_PR_ASSISTANT_END_MARKER = "<!-- git-ai:pr-assistant:end -->";
export const ALL_PR_ASSISTANT_START_MARKERS = [
  PR_ASSISTANT_START_MARKER,
  LEGACY_PR_ASSISTANT_START_MARKER,
] as const;
export const ALL_PR_ASSISTANT_END_MARKERS = [
  PR_ASSISTANT_END_MARKER,
  LEGACY_PR_ASSISTANT_END_MARKER,
] as const;

export const ISSUE_PLAN_COMMENT_MARKER = "<!-- prs:issue-plan -->";
export const LEGACY_ISSUE_PLAN_COMMENT_MARKER = "<!-- git-ai:issue-plan -->";
export const ALL_ISSUE_PLAN_COMMENT_MARKERS = [
  ISSUE_PLAN_COMMENT_MARKER,
  LEGACY_ISSUE_PLAN_COMMENT_MARKER,
] as const;

export const PR_REVIEW_COMMENT_MARKER = "<!-- prs:pr-review -->";
export const LEGACY_PR_REVIEW_COMMENT_MARKER = "<!-- git-ai-pr-review -->";
export const ALL_PR_REVIEW_COMMENT_MARKERS = [
  PR_REVIEW_COMMENT_MARKER,
  LEGACY_PR_REVIEW_COMMENT_MARKER,
] as const;

export const TEST_SUGGESTIONS_COMMENT_MARKER = "<!-- prs:test-suggestions -->";
export const LEGACY_TEST_SUGGESTIONS_COMMENT_MARKER = "<!-- git-ai-test-suggestions -->";
export const ALL_TEST_SUGGESTIONS_COMMENT_MARKERS = [
  TEST_SUGGESTIONS_COMMENT_MARKER,
  LEGACY_TEST_SUGGESTIONS_COMMENT_MARKER,
] as const;

export const ISSUE_TO_PR_COMMENT_MARKER = "<!-- prs:issue-to-pr -->";
export const LEGACY_ISSUE_TO_PR_COMMENT_MARKER = "<!-- git-ai:issue-to-pr -->";
export const ALL_ISSUE_TO_PR_COMMENT_MARKERS = [
  ISSUE_TO_PR_COMMENT_MARKER,
  LEGACY_ISSUE_TO_PR_COMMENT_MARKER,
] as const;

export const SETUP_SECTION_START = "<!-- prs:setup:start -->";
export const SETUP_SECTION_END = "<!-- prs:setup:end -->";
export const LEGACY_SETUP_SECTION_START = "<!-- git-ai:setup:start -->";
export const LEGACY_SETUP_SECTION_END = "<!-- git-ai:setup:end -->";
export const ALL_SETUP_SECTION_START_MARKERS = [
  SETUP_SECTION_START,
  LEGACY_SETUP_SECTION_START,
] as const;
export const ALL_SETUP_SECTION_END_MARKERS = [
  SETUP_SECTION_END,
  LEGACY_SETUP_SECTION_END,
] as const;

export const GENERATED_BY_SETUP_HEADER = "# Generated by prs setup";
export const LEGACY_GENERATED_BY_SETUP_HEADER = "# Generated by git-ai setup";

export const ACTION_REPOSITORY = "DevwareUK/prs";
export const LEGACY_ACTION_REPOSITORY = "DevwareUK/git-ai";

export const GIT_AI_ALIAS_DEPRECATION_MESSAGE =
  "`git-ai` is deprecated. Use `prs` instead.";

export function includesManagedMarker(
  body: string,
  markers: readonly string[]
): boolean {
  return markers.some((marker) => body.includes(marker));
}
