export const PRODUCT_SHORT_NAME = "prs";
export const PRODUCT_DISPLAY_NAME = "Pull Request Smith";

export const PACKAGE_SCOPE = "@prs";

export const REPOSITORY_STATE_DIRECTORY = ".prs";

export const REPOSITORY_CONFIG_RELATIVE_PATH = `${REPOSITORY_STATE_DIRECTORY}/config.json`;

export const PR_ASSISTANT_START_MARKER = "<!-- prs:pr-assistant:start -->";
export const PR_ASSISTANT_END_MARKER = "<!-- prs:pr-assistant:end -->";

export const ISSUE_PLAN_COMMENT_MARKER = "<!-- prs:issue-plan -->";

export const ISSUE_SPEC_COMMENT_MARKER = "<!-- prs:issue-spec -->";

export const PR_REVIEW_COMMENT_MARKER = "<!-- prs:pr-review -->";

export const TEST_SUGGESTIONS_COMMENT_MARKER = "<!-- prs:test-suggestions -->";

export const ISSUE_TO_PR_COMMENT_MARKER = "<!-- prs:issue-to-pr -->";

export const SETUP_SECTION_START = "<!-- prs:setup:start -->";
export const SETUP_SECTION_END = "<!-- prs:setup:end -->";

export const GENERATED_BY_SETUP_HEADER = "# Generated by prs setup";

export const ACTION_REPOSITORY = "DevwareUK/prs";

export function includesManagedMarker(
  body: string,
  markers: readonly string[]
): boolean {
  return markers.some((marker) => body.includes(marker));
}

export function startsWithManagedMarker(
  body: string,
  markers: readonly string[]
): boolean {
  const firstContentLine = body
    .split(/\r?\n/)
    .find((line) => line.trim().length > 0);
  return markers.some((marker) => firstContentLine?.trim() === marker);
}
