import { describe, expect, it } from "vitest";
import type { AuditTarget, RepositoryForge, RepositoryComment } from "./forge";
import {
  AUDIT_COMMENT_MARKER,
  publishAuditArtifact,
  renderAuditCommentBody,
} from "./audit-artifacts";

function comment(body: string): RepositoryComment {
  return {
    id: 7,
    body,
    url: "https://github.test/comment/7",
    createdAt: "2026-05-11T00:00:00.000Z",
    updatedAt: "2026-05-11T00:00:00.000Z",
    author: "prs[bot]",
    isBot: true,
  };
}

describe("audit artifacts", () => {
  it("renders a managed audit comment with a stable marker and section", () => {
    const body = renderAuditCommentBody({
      title: "Issue #42 audit",
      sections: [{ name: "Spec", content: "# Spec\n\nApproved." }],
      localRun: ".prs/runs/example",
    });

    expect(body).toContain(
      [
        AUDIT_COMMENT_MARKER,
        "",
        "prs automation note: this managed comment was generated by prs automation.",
      ].join("\n")
    );
    expect(body).toContain("## Spec");
    expect(body).toContain("# Spec\n\nApproved.");
    expect(body).toContain("Local run: `.prs/runs/example`");
  });

  it("rejects section names without marker-safe alphanumeric content", () => {
    expect(() =>
      renderAuditCommentBody({
        title: "Issue #42 audit",
        sections: [{ name: "!!!", content: "No marker id" }],
      })
    ).toThrow("Audit section name must contain at least one alphanumeric character.");
  });

  it("rejects duplicate normalized section marker IDs in one comment", () => {
    expect(() =>
      renderAuditCommentBody({
        title: "Issue #42 audit",
        sections: [
          { name: "Spec Review", content: "First" },
          { name: "Spec-Review", content: "Second" },
        ],
      })
    ).toThrow('Duplicate audit section marker ID "spec-review".');
  });

  it("creates a new issue audit comment when none exists", async () => {
    const calls: string[] = [];
    const forge = {
      type: "github",
      isAuthenticated: () => true,
      fetchAuditComment: async () => undefined,
      createAuditComment: async (_target: AuditTarget, body: string) => {
        calls.push(body);
        return comment(body);
      },
    } as unknown as RepositoryForge;

    const result = await publishAuditArtifact(forge, {
      target: { type: "issue", number: 42 },
      sectionName: "Plan",
      content: "Plan body",
      localRun: ".prs/runs/example",
    });

    expect(result.status).toBe("created");
    expect(calls[0]).toContain("## Plan");
  });

  it("updates an existing issue audit comment by replacing the named section and local run", async () => {
    const existing = renderAuditCommentBody({
      title: "Issue #42 audit",
      sections: [{ name: "Plan", content: "Old plan" }],
      localRun: ".prs/runs/old",
    });
    let updatedBody = "";
    const forge = {
      type: "github",
      isAuthenticated: () => true,
      fetchAuditComment: async () => comment(existing),
      updateIssueComment: async (_commentId: number, body: string) => {
        updatedBody = body;
        return comment(body);
      },
    } as unknown as RepositoryForge;

    const result = await publishAuditArtifact(forge, {
      target: { type: "issue", number: 42 },
      sectionName: "Plan",
      content: "New plan",
      localRun: ".prs/runs/new",
    });

    expect(result.status).toBe("updated");
    expect(updatedBody).toContain("New plan");
    expect(updatedBody).not.toContain("Old plan");
    expect(updatedBody).toContain("Local run: `.prs/runs/new`");
    expect(updatedBody).not.toContain("Local run: `.prs/runs/old`");
    expect(updatedBody).toContain(
      "prs automation note: this managed comment was generated by prs automation."
    );
  });

  it("inserts automation framing when updating a legacy audit comment", async () => {
    const existing = [
      AUDIT_COMMENT_MARKER,
      "",
      "# Issue #42 audit",
      "",
      "<!-- prs:audit:plan:start -->",
      "## Plan",
      "",
      "Old plan",
      "<!-- prs:audit:plan:end -->",
      "",
    ].join("\n");
    let updatedBody = "";
    const forge = {
      type: "github",
      isAuthenticated: () => true,
      fetchAuditComment: async () => comment(existing),
      updateIssueComment: async (_commentId: number, body: string) => {
        updatedBody = body;
        return comment(body);
      },
    } as unknown as RepositoryForge;

    await publishAuditArtifact(forge, {
      target: { type: "issue", number: 42 },
      sectionName: "Plan",
      content: "New plan",
    });

    expect(updatedBody).toContain(
      [
        AUDIT_COMMENT_MARKER,
        "",
        "prs automation note: this managed comment was generated by prs automation.",
        "",
        "# Issue #42 audit",
      ].join("\n")
    );
    expect(
      updatedBody.match(/prs automation note: this managed comment was generated by prs automation\./g)
    ).toHaveLength(1);
  });
});
