export const TOP_LEVEL_HELP = [
  "prs",
  "",
  "Deterministic local GitHub tools for Codex, Claude Code, and GitHub Copilot.",
  "",
  "Setup:",
  "  prs setup [--skills <none|codex|claude-code|copilot|all>]",
  "  prs skills install <codex|claude-code|copilot> [--json]",
  "  prs skills validate [--json]",
  "",
  "Issue tools:",
  "  prs tool issue list [--actionable] --json",
  "  prs tool issue context <issue-number> --json",
  "  prs tool issue ready <issue-number> [--unattended|--auto|--jdi] --json",
  "  prs tool issue publish-artifacts <issue-number> --spec-file <path> --plan-file <path> --json",
  "  prs tool issue create (--draft-file <path>|--issue-set <path>) --json",
  "  prs issue finalize <issue-number>",
  "",
  "Pull request tools:",
  "  prs tool pr list [--actionable] --json",
  "  prs tool pr ready <pr-number> [--unattended|--auto|--jdi] --json",
  "",
  "Audit:",
  "  prs tool token-usage render --file <path> --output <path> --json",
  "  prs tool token-usage capture --host <codex|claude-code|copilot> --output <path> [--session <id>] [--source <path>] [--since <ISO>] --json",
  "  prs audit publish (--issue <number>|--pr <number>) --file <path> --section <name>",
].join("\n");
